from __future__ import annotations
from typing import Protocol, Optional, List as tlist
from app.domain.models import Stock

class StockRepository(Protocol):
    def create(self, symbol: str, name: str) -> Stock: ...
    def list(self) -> tlist[Stock]: ...
    def get(self, stock_id: int) -> Optional[Stock]: ...